### ISSUE TITLE
Question about MAD formula

### ISSUE THREAD

**Issue by RichardPA** [ariaghora/robust-period#4]
I do not have a great understanding of math functions; however, I noticed a discrepancy between the MAD formula in robustperiod.py and the formulas I see online. I am most likely lacking in understanding and would appreciate any clarification.

The robustperiod.py MAD function is written as followed:
`def MAD(x):
    return np.mean(np.abs(x - np.median(x)))`

However, online resources are stating the MAD function is:
`(np.sum(np.abs(x-np.mean(x))))/n`
Where x is the input data and n is the number of data points.

Am I by chance looking at the wrong MAD function online? Thank you for any clarification.

Sincerely, 
Richard Panduro

**Comment by ariaghora** [comment]
Hi @RichardPA, you are correct. My initial commit used `mean`, but for some reason (forgot it, pardon me) I changed that to `median`. I updated the MAD formula, i.e., `median` into `mean`. Thank you for the catch.

Best, 
Aria

**Comment by dannypanduro** [comment]
That makes sense; thank you for the clarification! You've done a great job with this package. Thank you. 

Bests,
Richard
